version: "3.8"
services:
  dbt:
    build:
      context: ./dbt_stocks
    container_name: dbt-postgres
    ports:
      - 8082:8082
    volumes:
      - ./dbt_stocks:/usr/app
      - ${USERPROFILE}/.dbt:/root/.dbt
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    command: ["run"]

networks:
  etl-net:
    name: etl-net
